// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TV_Infrastructure;

#nullable disable

namespace TV_Infrastructure.Migrations
{
    [DbContext(typeof(TVDBContext))]
    [Migration("20240816041738_adding-const-guid-id-for-list-languages")]
    partial class addingconstguididforlistlanguages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TV_Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TVShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TVShowId")
                        .IsUnique();

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("TV_Domain.Languages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a25aeca6-cfc9-43d1-96b9-e4f3530ef7fb"),
                            IsDeleted = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("79be201e-37d4-4c65-814b-e726d61ac82c"),
                            IsDeleted = false,
                            Name = "Arabic"
                        });
                });

            modelBuilder.Entity("TV_Domain.TVShow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("TV_Domain.TVShowLanguages", b =>
                {
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TVShowID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IsDeleted");

                    b.HasIndex("LanguageID");

                    b.HasIndex("TVShowID");

                    b.ToTable("TVShowLanguages");
                });

            modelBuilder.Entity("TV_Domain.Attachment", b =>
                {
                    b.HasOne("TV_Domain.TVShow", "TVShow")
                        .WithOne("Attachment")
                        .HasForeignKey("TV_Domain.Attachment", "TVShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("TV_Domain.TVShowLanguages", b =>
                {
                    b.HasOne("TV_Domain.Languages", "Languages")
                        .WithMany("TVShowLanguages")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TV_Domain.TVShow", "TVShow")
                        .WithMany("TVShowLanguages")
                        .HasForeignKey("TVShowID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Languages");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("TV_Domain.Languages", b =>
                {
                    b.Navigation("TVShowLanguages");
                });

            modelBuilder.Entity("TV_Domain.TVShow", b =>
                {
                    b.Navigation("Attachment")
                        .IsRequired();

                    b.Navigation("TVShowLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
